### ISSUE TITLE
[Todo] Add back square and circle API

### ISSUE THREAD

**Issue by dhs17y2adonchia** [zaydek/duomo#156]

**Comment by zaydek** [comment]
Problem with square and circle is whether or not stacks need to know about them because of the `--dm-align-self` pattern. In theory we can put square and circle before w- and h- so we can still override them, if need be. But yeah, this API would probably need to be stack-aware to work intuitively. The same can be said about aspect ratios.

**Comment by zaydek** [comment]
Since I can’t think of an elegant way to do this because of the `--dm-align-self` hidden CSS variables I use to invoke auto-centering, I’m going to close this for now. If we can get rid of that pattern, this would be fine to support.

**Comment by zaydek** [comment]
Now that we’re not doing fancy BS with stacks we should be able to add this back.

**Comment by zaydek** [comment]
These should probably leverage the `sizes()` getter. If the output size is too much this will likely not be added. Depends on cost to output size.

**Comment by zaydek** [comment]
I probably won’t add this just because it unnecessarily adds to the output size. That being said, if a user wanted to implement this themself it would be awfully easy with the new getter APIs.
